name: Deploy Docs to PaaS
on:
  push:
    branches:
      - main

jobs:
  deploy-to-paas:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install cf client
        env:
          CF_CLI_DOWNLOAD_URL: https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v7
        run: |
          echo "::group:: Download cf CLI"
          curl -sL ${CF_CLI_DOWNLOAD_URL} | sudo tar -zx -C /usr/local/bin
          cf version
          echo "::endgroup::"
      - name: cf login
        shell: bash
        run: |
          cf api ${CF_API_URL}
          cf auth
          cf target -o ${CF_ORG_NAME} -s ${CF_SPACE_NAME}
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: docs
          CF_ORG_NAME: gds-digital-identity-authentication
          CF_API_URL: https://api.london.cloud.service.gov.uk

      - name: Build
        run: bundle exec middleman build

      - name: Create Credentials
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          COOKIE_SECRET: ${{ secrets.PROXY_COOKIE_SECRET }}
        run: |
          set +e
          export CREDENTIALS="$(jq -n '{ client_id: $client_id, client_secret: $client_secret, cookie_secret: $cookie_secret }' \
            --arg client_id "${CLIENT_ID}" \
            --arg client_secret "${CLIENT_SECRET}" \
            --arg cookie_secret "${COOKIE_SECRET}" \
          )"
          cf service auth-tech-docs-proxy-credentials > /dev/null
          if [[ $? == 0 ]]; then
            cf update-user-provided-service auth-tech-docs-proxy-credentials -p "${CREDENTIALS}"
          else
            cf create-user-provided-service auth-tech-docs-proxy-credentials -p "${CREDENTIALS}"
          fi

      - name: Push to PaaS
        run: cf push

      - name: Create Network Policies
        run: cf add-network-policy di-auth-tech-docs-proxy di-auth-tech-docs-website --protocol tcp --port 8080